name: Build, Test, Dockerize & Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from git tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.vars.outputs.VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.vars.outputs.VERSION }} ${{ secrets.DOCKER_USERNAME }}/testapi:latest

      - name: Push both versioned and latest Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.vars.outputs.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/testapi:latest
