name: Build, Test, Dockerize & Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.get-latest-tag.outputs.tag }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.get-latest-tag.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/testapi:latest

      - name: Push both versioned and latest Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/testapi:${{ steps.get-latest-tag.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/testapi:latest
